### ISSUE TITLE
[Info] iodine vs falcon vs puma

### ISSUE THREAD

**Issue by waghanza** [boazsegev/iodine#102]
HI @boazsegev,

I'm adding tests for (some) `ruby` **framework** using `iodine` in https://the-benchmarker.semaphoreci.com/workflows/ce7d732e-e28b-44f5-ba19-5843cb32fe07?pipeline_id=9051f815-5861-4597-be99-2ba582bf6e2e

Regards,

**Comment by boazsegev** [comment]
Hi @waghanza ,

Thanks for opening this issue and the info.

Since it's related to #103 I'll be closing this one too.

P.S. (Side-Note),

Benchmarking iodine against Puma might be biased when running iodine in its default concurrency setting - this is especially true when puma is started in cluster mode with a single thread (`-w $(nproc)`), as it seems to be.

Running iodine with the same `-w $(nproc)` might remove some of the bias in the benchmarks (though different servers really should have different concurrency optimizations in place).

Kindly,
   Bo.
