### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [boazsegev/iodine#137]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by boazsegev** [comment]
Hi @HoangNgo88 ,

Thank you for your interest and the question.

The fact is that I chose Redis because I was familiar with it from other projects. I knew I could write an easy protocol implementation (so I could keep the license MIT) and that its fast (memory bound rather than disk bound).

Also, I'm just one person writing the underlaying C project (facil.io). I was assuming that if other people will desire a different pub/sub backend, than they can patch it up themselves. The code I wrote for connecting to Redis could be used as a template.

IMHO, Redis has a number of advantages: it's single threaded, so no race conditions; it uses in-memory storage rather than disk storage, which makes it fast; its open source and the source code is solid (I read some and was joyfully impressed).

On the other hand, Redis has cons as well; It's difficult to shard / horizontally scale; it uses (at least) 2 connections per client; it publishes messages to the client that originally published them (wasting bandwidth and resources)...

RabbitMQ and Kafka have different pros/cons as they are designed with a different use cases in mind (i.e., keeping a record that can be replayed and used as a source of "truth", rather than simply publishing events). So it really depends on what you need rather than which one is best.

Anyway, good luck and thanks for asking.
