### ISSUE TITLE
Dropped connections?

### ISSUE THREAD

**Issue by richardriman** [boazsegev/iodine#14]
Hi, I trying your server and have one issue. My web application needs to load a bunch of data about issues so I split to ten or so chunks and made parallel requests. Browser process them in batches of two (send 2 request, wait for response, next two, etc.).

When I run puma with -t 1 -w 4, everything is ok. But if I run your server with same settings -t 1 -w 4, some connections are properly handled and some are failed with empty response. With -t 2 -w 4 everything goes well. I'm really not sure what can do it, but it's definitely not a problem with my application because on every other tested server everything is OK (tested with webrick, unicorn, puma, passenger and thin).

Also, have you done some benchmarks? In my scenario with these issues, I have pretty slow requests in general as you can see, it's because this is a pretty complex application, entities are big and with many nested entities. I experienced that your server has significantly slower responses then e.q. puma (about 30 - 50% slower).

![screenshot 2017-05-16 13 40 58](https://cloud.githubusercontent.com/assets/620832/26104979/81c217aa-3a40-11e7-8ed9-6f71c263566c.png)

**Comment by boazsegev** [comment]
Hi @richardriman ,

Thank you for opening this issue and exposing the problem.

I haven't recreated the issue on my machine, but I'll try to do so tonight.

#### As to the issue of dropped connections (and a possible workaround)

I suspect the dropped connections are related to the connection timeout review in the single-threaded mode.

Iodine will drop inactive HTTP connections after 5 seconds, protecting your machine from slow clients. Once the application starts handling a request, the connection is marked as "busy" and will remain "safe" for 5 minutes or so...

... however, in your example, it seems that the application is busy... , so connections waiting to be handled aren't marked as busy and are being dropped the moment control is returned to the server (on a single threaded application, the server has no background threads).

If this is the issue (I have to test first), than an update to the timeout mechanism might fix it.

For now, a **workaround** , would be to increase the timeout settings within the application (this isn't available as a terminal option, but I'll add it), using:

```
Iodine::Rack.timeout = 20 # 20 seconds instead of the default 5
```

If this prevents the dropped connections, please let me know, as it means the issue is definitely with the code in the timeout review.

#### The issue of Performance

I'm very sorry (and surprised) to read about the performance you're experiencing and I will work on fixing this as soon as I can.

With my benchmarks and tests, iodine performed significantly better than other Ruby servers, but I don't think I tested it against large dynamic responses in single threaded mode.

I'm not sure about the source of the issue, but I suspect this issue is closely related to the big response sizes and it might have to do with memory consumption limits I coded into the server and the fact that there's only one thread shared between the application and the server.

I'll explain:

1. Each iodine process has a user-land buffer limit for outgoing dynamic data (files behave differently and are streamed from the disk, not from memory).

 Once the buffers are full, the iodine worker will block until enough buffers become available to send the blocked response (that is effected by the size of the response).

 This helps load balancing, so new connection are routed to other workers.
 
2. I also think that having only one thread prevents iodine from sending / receiving data while your application is busy.

 I didn't anticipate large responses to be handled in single threaded mode and I should probably add a dedicated IO thread that makes sure that data is being sent even when your application is busy/blocking the single thread. This might help fix this issue.


I'll try to recreate the issue later tonight and work on a fix for both the performance issue and the timeout experience.

Again, thank you for opening this issue and helping me make iodine the best server it could be.

Kind Regards,
  Bo.

**Comment by boazsegev** [comment]
SIDENOTE:

Iodine has the great advantage of implementing native (server side) websockets.

It's possible that your specific application might run smoother if these fragmented pieces of data were sent using a websocket connection.

This will allow you to subdivide into smaller fragments and use a single persistent connection. This approach should increase performance, boost perceived performance (client side responsiveness/rendering) and open the door for micro updates for a specific fragment of the data.

Kind regards,
   Bo.

**Comment by richardriman** [comment]
Hi, testing new release, there is my report.

With -tout 20 (or 10) there is no more dropped connections. Performance using one thread is now also better, not sure how much due to this request has pretty inconsistent response times. But I have also some fast request so look at it.

Because the -t 1 is edge case, only for my testing purposes, use something more real, e.q. -t 2 -w 4 and compare puma and iodine on exactly the some but real request. I have some polling for issues updates.

Puma responds in 56 - 59ms from the first request and remain consistent in long run.

Iodine responds in about 350ms for a first few requests, probably loading application code (I using app preloading with puma). After warm-up responds in 57 - 67ms which is a little less consistent then puma. But in time it goes more consistent, response times now seems even better than puma, 53 - 58ms. From time to time one request has a little worse response time, about 61ms, probably GC?

There is one interesting thing about your server and this is, response size are smaller from Iodine (512 vs 480 bytes). Probably different headers, because response body is exactly the same.

**Comment by richardriman** [comment]
Once I stopped the server with Ctrl + C, I got a segmentation fault.

![screenshot 2017-05-17 10 48 44](https://cloud.githubusercontent.com/assets/620832/26147223/29b60946-3af3-11e7-9973-05f176bba67d.png)

**Comment by richardriman** [comment]
By the way, thanks for the great tip about streaming issues over websocket! Maybe I'll try it when I have a little time.

**Comment by boazsegev** [comment]
@richardriman , thanks for all the data and the testing - this is very helpful.

After many tries, I managed to replicate the segmentation fault by pure luck... It seems to come and go and I guess it has to do with the IO thread (since it might be running tasks during cleanup). 

I'll try to patch it up soon, but since it doesn't seem to effect the actual server, it could probably wait. Also, it's bit too rare on my machine for me to know for sure.

Puma still runs slower on my machine than iodine, which means my test applications don't work hard enough and doesn't manage to emulate your environment.

Later today I'll try installing Ruby 2.2 and see if the issues might be more pronounced. I use Ruby 2.4.1, so the performance and the other issues might be affected.

Are you testing this through a framework? if so, could there be other considerations I didn't look into?

It would be great if you already have an example that will replicate the crash, so I could test it on my machine and patch things up Tried serving large data, but this doesn't seem to effect my machine.

As for warmup, iodine provides a limited warmup features by using:

```
iodine -warmup
```

Thank you very much for exposing these issues.

**Comment by richardriman** [comment]
I'm trying to reproduce the segmentation fault but without success.

My actual stack is Rails 3.2.22.5 and Ruby 2.1.10 (iodine don't support 2.1 so I use 2.2.6 for testing which is a highest Ruby I can safely use with my Rails application).

**Comment by boazsegev** [comment]
**Side-Note:**

I hope this tip helps, but I would consider that [support for 2.1 has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/) and support for 2.2 is only limited to security fixes and will be completely dropped by March 2018 (which is almost around the corner).

It's possible to upgrade slowly by using two stacks instead of one, i.e., by using ActiveRecord for old code and Squel for new code. This allows you to run old code and new code together, gradually upgrading as you go.

Also, I know Rails 5 is almost a new language. This separation of code allows you to separate between the application and the routing layer (the web framework), making future upgrades easier and allowing to upgrade or change frameworks (or even use plain Rack) with a smaller penalty.

**Comment by boazsegev** [comment]
I'm reading through the notes again to make sure I understand the problems left.

If I understand correctly, the issues are/were:

* Dropped connections - solved using a workaround (the `-tout` + having another thread performing IO even in single threaded mode).

* Performance is slower on Iodine for big requests (or is it also small requests?).

I read about the performance tests and I wonder - how are you measuring performance?

On all my tests, iodine performs better than puma.

On my computer I set up the following application (placed in `config.ru`, [here's a link to the actual code](https://github.com/boazsegev/iodine/blob/7d36e0085b1cc4535dd33053dbc6785fb32b757a/bin/config.ru)):

```ruby
app = proc do |_env|
  logo_png ||= IO.binread './logo.png'
  [200, { 'Content-Length'.freeze => logo_png.length.to_s , 'Content-Type'.freeze => 'image/png'.freeze}, [logo_png]]
end
run app
```

My `logo.png` file is 134Kb. But I send it as a string instead of using the static file service (on iodine, this will be `-www ./public`).

Than I run Puma or Iodine using `-w 1 -t 1 -p 3000`.

I'll test with `wrk -c200 -d4 -t12 http://localhost:3000/` which runs the test for 4 seconds, using 12 threads and 200 concurrent requests at a time.

On my machine, I get (best out of 1 warmup + 3 runs):

**Puma** 
```text
Running 4s test @ http://localhost:3000/
  12 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   108.19us   44.96us   8.03ms   98.32%
    Req/Sec     9.07k   332.18     9.33k    97.56%
  37014 requests in 4.10s, 4.73GB read
  Socket errors: connect 0, read 47, write 0, timeout 0
Requests/sec:   9030.27
Transfer/sec:      1.15GB
```
**Iodine**

```text
Running 4s test @ http://localhost:3000/
  12 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.73ms    1.06ms  25.04ms   83.83%
    Req/Sec     0.85k    55.39     0.97k    77.60%
  41786 requests in 4.10s, 5.35GB read
  Socket errors: connect 0, read 51, write 0, timeout 0
Requests/sec:  10181.92
Transfer/sec:      1.30GB
```

Iodine obviously shows higher latency (notice the units) but it's overall performance seems better.

I assume that if I had a slower client or a proxy in the middle, the throttling would hit me sooner or harder, but on my local machine I didn't even feel it.

I tried it on Ubuntu, using a virtual machine which a slower proxy layer...

...The slower proxy layer should increase memory consumption by the server layer, since it needs to keep the sent data in the memory for more time. Puma doesn't enforce memory limits, but iodine does, so it should have been more affected.

I started with 50 concurrent requests and continued to 200, 1000 and 2000 concurrent requests (On Ubuntu with slower proxy)):

**puma**

``` text
Running 4s test @ http://localhost:8080/
  12 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.13ms  170.74us   7.02ms   81.96%
    Req/Sec     0.89k    19.47     0.92k    85.37%
  3619 requests in 4.10s, 473.31MB read
  Socket errors: connect 0, read 59, write 0, timeout 0
Requests/sec:    883.01
Transfer/sec:    115.48MB

Running 4s test @ http://localhost:8080/
  12 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.30ms  287.92us  13.00ms   96.41%
    Req/Sec   772.15     35.98   828.00     75.61%
  3150 requests in 4.10s, 412.02MB read
  Socket errors: connect 0, read 310, write 0, timeout 0
Requests/sec:    768.67
Transfer/sec:    100.54MB

Running 4s test @ http://localhost:8080/
  12 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.38ms  547.25us  27.86ms   99.02%
    Req/Sec   726.76     51.35   797.00     87.80%
  2965 requests in 4.10s, 387.82MB read
  Socket errors: connect 0, read 473, write 0, timeout 0
Requests/sec:    722.73
Transfer/sec:     94.53MB

Running 4s test @ http://localhost:8080/
  12 threads and 2000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.41ms    1.06ms  54.82ms   99.57%
    Req/Sec   708.40     72.70   760.00     97.50%
  2821 requests in 4.08s, 368.96MB read
  Socket errors: connect 0, read 603, write 0, timeout 0
Requests/sec:    690.80
Transfer/sec:     90.35MB

```

**iodine**

``` text
Running 4s test @ http://localhost:8080/
  12 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.18ms   12.76ms  81.32ms   71.32%
    Req/Sec    99.00     16.41   160.00     49.38%
  4763 requests in 4.04s, 625.21MB read
  Socket errors: connect 0, read 23, write 0, timeout 0
Requests/sec:   1180.25
Transfer/sec:    154.92MB

Running 4s test @ http://localhost:8080/  12 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    54.84ms   36.73ms 199.95ms   68.61%
    Req/Sec    98.81     37.35   202.00     63.31%
  4724 requests in 4.03s, 619.02MB read
  Socket errors: connect 0, read 341, write 0, timeout 0
Requests/sec:   1172.82
Transfer/sec:    153.68MB

Running 4s test @ http://localhost:8080/
  12 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    76.69ms   32.20ms 169.34ms   65.79%
    Req/Sec    78.73     52.80   360.00     80.43%
  3718 requests in 4.05s, 488.26MB read
  Socket errors: connect 0, read 126, write 1, timeout 0
Requests/sec:    918.53
Transfer/sec:    120.62MB

Running 4s test @ http://localhost:8080/
  12 threads and 2000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   170.22ms   87.12ms 651.09ms   68.14%
    Req/Sec    76.31     43.19   380.00     69.98%
  3578 requests in 4.04s, 470.23MB read
  Socket errors: connect 0, read 428, write 1, timeout 0
Requests/sec:    884.65
Transfer/sec:    116.26MB
```

The throttling was a happy coincidence and it wasn't a planned feature... At the moment, [the memory usage for the socket buffer is capped at 16Mib](https://github.com/boazsegev/iodine/blob/7d36e0085b1cc4535dd33053dbc6785fb32b757a/ext/iodine/libsock.h#L37-L46), after which sending requests slows down... but still, as you can see, iodine's performance is very high.

If you feel there's something I'm missing, please let me know.

Thank you for helping me dig into this,
   Bo.

**Comment by boazsegev** [comment]
@richardriman I wanted to thank you again for pushing me about performance.

Your questions and concerns are helping me test and improve iodine, bringing it closer to a 1.0 release.

For example, I explored ways to minimize the latency you mentioned. I also started to explore a more fragmented design with more safety nets, so issues like the connection timeout review might become more integrated and responsive to real-time changes.

I started to [rewrite the core C framework](https://github.com/boazsegev/facil.io/tree/core-rewrite) which will be eventually merged to [facil.io's master branch](https://github.com/boazsegev/facil.io) once I bridge the existing code with the new core's API (adding the missing core features where required).

This will obviously take a while, but I hope to release a working 0.3 development version this summer.

Thanks again,
   Bo.

**Comment by boazsegev** [comment]
@richardriman , I thought you'd be happy to know I just released Iodine version 0.3.0, with the C core rewritten and after running many tests I can say it should be a major performance boost.

However, as You can read in [the added section to the README](https://github.com/boazsegev/iodine#performance-oriented-design---but-safety-first), the use of a single thread in a slower application should be (usually) avoided.

Thanks again for the push. I love the results of this extra effort I put into this gem.
B.

**Comment by richardriman** [comment]
Hi, thx for info about new release with performance improvements. I really don't use one thread, it was only a testing scenario and big coincidence I was catch some bugs. :)

**Comment by richardriman** [comment]
Hah, rack >= 2.0 is blocker for me. I can still use iodine on few smaller projects but for our primary application it's impossible. :(

**Comment by richardriman** [comment]
Rack 2 in RoR world is usable since Rails 5. I think there still are many people running on Rails 4.2.

**Comment by richardriman** [comment]
BTW, with the "Squel", you mean this? http://sequel.jeremyevans.net/

**Comment by boazsegev** [comment]
Thanks for the info!

I'm releasing a fix for the Rack issue right now... It was bundler that was complaining about the lack of a specific Rack version description, iodine doesn't really care about the Rack version. The API iodine uses seems to have stayed consistent between the versions.

As to sequel, than yes, definitely that one... It's just one option, but it's a great option. I love both sequel and ActiveRecord, but I found Sequel less demanding.
