### ISSUE TITLE
How to get client instance id

### ISSUE THREAD

**Issue by rschwass** [boazsegev/iodine#149]
When a client connects I would like to store that client in a DB depending on where it came from. 

So that I can then when that client closes depending on its origin remove it from an array.

So if I have a web controller that opens a client and passes an optional param I can say this client.id gets stored in a table due to parameters passed when it was created.

Then when the "on_close" happens I check if the client doing the closing is stored in my table or not.

**Comment by rschwass** [comment]
`def initialize(shellid, channel, controller = 0)`

so when i init the client, i specify controller=1 , how do i think store that clients "ID" that I can parse when each client closes?

**Comment by boazsegev** [comment]
@rschwass , thank you for opening this issue and for your interest in iodine.

Since [the HTTP request's `env` Hash object is accessible through `client.env`](https://www.rubydoc.info/gems/iodine/Iodine/Connection#env-instance_method), it should be quite easy to produce a UUID and assign it to the connection. It should be quite easy to store this connection's UUID as well as the originating processes' ID in a database of some sorts...

However, for most use cases, this approach would create scalability issues.

For example, assuming you want to create an "online" indicator for a user: How do the connection indicators link to a specific user? What would happen if a user comes online on two different browsers, or on a browser + app? Does each connection get a different uuid? What if two different machines handle these connections? What if a server crashes or goes offline before calling the connection's `on_closed` callback?

Much better to handle this as a user related event, using the user's ID rather than the connection ID, separating the `online/offline` responsibility from the connection object.

i.e., publish an `{event: "connected", user: "me@id.com", at: Time.now}` or an event `{event: "disconnected", user: "me@id.com", at: Time.now}`. Let the event handler (which might be a different micro-service) increase or decrease a user associated `online` counter. Perhaps add a `last-seen` indicator, or a timer, or listen to some user produced events (such as `ack` events), so the online count is reset if a client doesn't answer a `ping` or appears inactive for too long (having a browser open doesn't mean the person is still there)...

Suddenly, instead of handling connections, you focus on the user itself - a much more relevant entity.

I hope this helps. I wish you the best of luck.
