### ISSUE TITLE
HTTPS and HTTP2 support

### ISSUE THREAD

**Issue by rfestag** [boazsegev/iodine#17]
This is more of a question, but are there plans for HTTPS/HTTP2 support? I notice in your README that supporting HTTP2 was one of the reasons for starting this project, but then I only notice HTTP 1.1 support.

I was considering adding support via the http-2 gem, but then I couldn't find any information on setting up SSL. Am I missing something in how to configure that, or is SSL not supported yet?

**Comment by boazsegev** [comment]
Hi @rfestag ,

Thank you for your interest.

I just finished a big refactoring of the HTTP protocol management system (it's all written in C and organized under the [`facil.io` C library repo](https://github.com/boazsegev/facil.io)).

By creating virtual function references for `http_request` and `http_response` it's now possible have transparent HTTP/2 support. By adding support for a `set_rw_hooks` callback, it's now possible to transparently hook-up any TLS/SSL layer implementation... these things are on my roadmap for the high performance C layer.

But I have to admit that both TLS/SSL and HTTP/2 support keeps getting pushed back because [most apps handle HTTP/2 and TLS/SSL using the proxy layer](https://www.reddit.com/r/ruby/comments/6fd3cl/interview_aaron_patterson_rack_github_and_bbq/)...

... This means that adding support for pub/sub using both cluster channels (local "machine" pub/sub) and Redis channels (global pub/sub) will probably benefit more applications than both HTTP/2 and TLS/SSL combined.

So, at the moment my focus is on pub/sub support for the web socket layer... you might have noticed (if you looked at the C source code file names) that there's an unused pub/sub API that Iodine doesn't expose just yet (the Redis part isn't ready).

I'm just one person working on this in my spare time without any backing or support, so these things happen is sporadic leaps and pauses between my projects and studies (my musical life comes first).

I wish everything on my road map was available... but there's more work to be done. The current roadmap looks like this:
* Cluster pub/sub (I think I finished this part last night, I just didn't connect it to Iodine).
* Native Redis pub/sub.
* Attach pub/sub to the Iodine API.
* Transparent `gzip` static file support.
* Iodine client mode using `connect` and `attach`.
* `ws` Websocket client.
* Transparent HTTP/2 support.
* TLS/SSL support.
* (Re)designing the Iodine API to match the TLS/SSL support by allowing multiple HTTP Rack servers to run at the same time (allowing for both a TLS and a non-TLS gateway).
* `wss` Websocket client.

Anyway, I hope I didn't write more information than you asked for.

Thank you again for your question and interest.
Bo.
