### ISSUE TITLE
Is rake-compiler a runtime dependency?

### ISSUE THREAD

**Issue by luislavena** [boazsegev/iodine#19]
Hello,

I've noticed that `rake-compiler` is being a runtime dependency of this project (iodine), however, I'm not clear how that is used at runtime.

rake-compiler provides a series of tools for gem authors **during development** and is not aimed to be added as runtime dependency.

You can think of rake-compiler the same way you think of rake and rspec: those are tools that help you build your library, but not necessarily dependencies you want to transfer at runtime to the end user.

Could you confirm the expected need for this dependency?

Thank you. :heart: :heart: :heart:

**Comment by boazsegev** [comment]
@luislavena ,

Thank you for opening this issue.

I think you're right. It should be a development dependency. Although Iodine does not come pre-compiled, I don't think `rake-compiler` is required in order to compile the gem during installation (I think the builtin `mkmf` is used).

I should probably fix this before the next release.

👍🏻

**Comment by luislavena** [comment]
Thank you.

indeed `mkmf` is used during `gem install` as long the gem defines the `extensions` part in the gemspec, so I believe all good with this.

Please let me know once you perform a new release so I can update the dependencies of [bench-micro](https://github.com/luislavena/bench-micro).

Thank you. :heart: :heart: :heart:

**Comment by boazsegev** [comment]
I just released the updated version (0.4.1).

This should fix the dependencies 👍🏻

Thank you 💜💛❤️

**Comment by luislavena** [comment]
Awesome!!! :heart_eyes_cat: :heart: :heart:
