### ISSUE TITLE
Possible memory issue when using Iodine with Sinatra and publish in server process 

### ISSUE THREAD

**Issue by haukot** [boazsegev/iodine#27]
Hi!

I found that the server throws strange errors without backtrace in the case when it runs with Sinatra and uses publish \ subscribe for server processes.

Video with the problem reproduction:
https://youtu.be/c5AWvsdX0AE
Repo with test code:
https://github.com/haukot/iodine_issue

Errors are similar to these:
```
Iodine caught an unprotected exception - NoMethodError: undefined method `call' for "ensure in block in singleton class":String
Iodine caught an unprotected exception - NotImplementedError: method `call' called on unexpected T_IMEMO object (0x000000018bd660 flags=0x405a)
Iodine caught an unprotected exception - NoMethodError: undefined method `call' for "^xml(\\s+(.+))?$":String
Iodine caught an unprotected exception - NoMethodError: undefined method `call' for #<Array:0x000000028494d0>
Iodine caught an unprotected exception - NotImplementedError: method `call' called on unexpected T_NODE object (0x0000000163d778 flags=0x35491b)
Iodine caught an unprotected exception - NoMethodError: undefined method `call' for "/home/haukot/.rvm":String
```

It seems that the process captures a random memory. Usually these errors don't do anything, and even messages are written to client sockets correctly. But sometimes messages not written, and once the entire server has crashed. This is error dump:
https://github.com/haukot/iodine_issue/blob/master/error_dump

In other cases (in particular, if the Slim template is not used), the server writes errors like this:
```
ERROR: (pub/sub) cluster message size error. Message ignored.
```

P.S. It would be really cool if you have any ideas how to show any backtrace in such situations, even if it will be C backtrace. Otherwise it's quite difficult to localize the problem.

**Comment by boazsegev** [comment]
Hi @haukot ,

Thank you so much for opening this issue! 🙏🏻👍🏻

I couldn't recreate it on my computer, but I think I just needed to give the app more time.

I certainly found an issue when reading through the code (the code didn't "register" the Ruby `block` in iodine's "Registry", meaning the GC would probably collect the block after a while and recycle the memory).

I didn't release the fix yet because I couldn't test it on my computer.

Would you mind installing from source and testing (`master` == 0.4.18, `v.0.5-rewrite` == 0.5.0)?

Thanks!!!
   B.

P.S.:

1)

Did I spell you name correctly in the CHANGELOG? or do you prefer I use the Russian spelling?

2)

As a side note I should probably point out that version 0.5.0 is a big rewrite. The pub/sub engine was completely redesigned (it should be faster and it should use less memory... but I did drop some features that weren't supported when using Redis or that were confusing for some developers).

It would make sense to test against version 0.5.0 to make sure the code will work on the upcoming version.

**Comment by haukot** [comment]
Yes, the problem with memory gone in both versions, thank you!

However, this error message still showed up in the test app that I send(but funny not the one I'm working on) in version 0.4.18
```
ERROR: (pub/sub) cluster message size error. Message ignored.
```
but despite this all messages are delivered correctly. 

1. I prefer 'Dmitry Davydov', but your variant also correct
2. Okay, thank you for the notice! Sure, I'll test app in version 0.5.0 when it comes.

**Comment by boazsegev** [comment]
Thank you for your quick response and for testing the patch before it was released.

> It would be really cool if you have any ideas how to show any backtrace in such situations, even if it will be C backtrace. Otherwise it's quite difficult to localize the problem.

I agree... but iodine's engine (facil.io) is an evented framework, which means that the backtrace is usually meaningless and often misleading (the error is often caused by the function that scheduled the event rather than the function handling the event).

> this error message still showed up in the test app that I send (but funny not the one I'm working on) in version 0.4.18
>
>          ERROR: (pub/sub) cluster message size error. Message ignored.

I finally managed to reproduce the issue. I didn't solve it ye (it's somewhere in the old pub/sub engine, so it might take me a while.

> but despite this all messages are delivered correctly.

I hope you are right, but I think this would indicate a message being dropped. I'm looking into it.

**Side note**:

You code has the following line:

```ruby
::Iodine.subscribe(channel: :internal) {|_, m| puts m }
```

This line will make a subscription for each iodine process.

Maybe you could consider limiting the subscription to a single process, like this:

```ruby
ROOT_PID = Process.pid()
::Iodine.run do 
  if(Process.pid == ROOT_PID)
     ::Iodine.subscribe(channel: :internal) {|_, _| 'nothing' }
  end
end
```

This will minimize processing. It will also allow for easier to use pub/sub to forward the processed data without getting duplicate messages.

**Comment by boazsegev** [comment]
Solved. 🎉

The reason for the error was the use of `memcpy` where `memmove` should have been used (overlapping memory addresses).

This wasn't an issue on BSD systems (such as macOS) because both function behave the same on BSD. However, on Linux the difference could cause memory corruption.

I managed to replicate the issue on my Linux VM, which allowed me to track it down.

I just released an updated gem with the patch (version 0.4.18).

I hope it works as expected.

P.S.

I'm happy to see how differently you're using the pub/sub features. I didn't get to use them this way (I mostly push directly to the client rather than process the data on the server).

Please let me know if you run into any other issues :-)

Thanks again for opening this issue! 🙏🏻👍🏻

**Comment by haukot** [comment]
Yes, the problem has gone, thanks!

I'll be happy to say how I use Iodine because I anyway wanted to ask a couple questions =)
And also there were a few cases when it was necessary to supplement the current functionality of Iodine, so I hope this will be useful =)

I'm currently working on integrating Iodine as a backend to LiteCable(https://github.com/palkan/litecable/pull/10).

LiteCable is a more lightweight version of ActionCable that you can use without Rails. LiteCable aims to be compatible with Action Cable as much as possible - for example you can use the js code from ActionCable without changes.

LiteCable (and ActionCable) have stream abstractions (like channel in Iodine, used for pub/sub) and Channel (a logical unit, I'll call it with capital C to distinguish from channels in Iodine).
Each Channel can subscribe to one or several streams, and clients (from the frontend for example) subscribe to the Channels.

With this I discovered three problems with integration.


1. The first problem is that the method `Litecable.broadcast(stream, message)` works differently than Iodine.publish.

Yes, it also sends a message to all connected clients, but since customers subscribe not to streams, but to Channels, it must also add channel_id (identifier) to messages - because websocket connection is the same for several Channels on the page.
So the command
```ruby
LiteCable.broadcast "chat_room_1", user: "dima", message: "some", sid: "1521049376518"
```
will dispatch on all clients that are subscribed on Channels that are subscribed to the stream chat_room_1, and add to it the message channel identifier, for example:
```js
{identifier: '{"channel":"chat","id":"room_1"}', message: {user: "dima", message: "some", sid: "1521049376518"}}
```
for client thats are subscribed for Chat channel 
```js
{identifier: '{"channel":"admin_notification","id":"room_1"}', message: {user: "dima", message: "some", sid: "1521049376518"}}
```
for clients that are subscribed for AdminNotification channel 

In the current solution, I store all the `stream => [channel, socket]` combinations in the ruby, inside the server process. That is, each process stores its own map. 
To be able to broadcast on all clients of all processes, each process is subscribed to the system channel - for example `:internal`.

And when `Litecable.broadcast` is called, we do `Iodine.publish(channel: :internal)`, and each process inside itself makes a loop by sockets, adds the channel identifier and calls `socket.write`.

So that because this code is without root_id - we need a subscription from all server processes
```ruby
::Iodine.subscribe(channel: :internal) {|_, m| puts m } 
```
In general, it looks like this (simplified):

```ruby
map = {
  chat_stream: {
    'chat_channel': [socket1, socket2], 
    'another_channel': [socket3]
  }, 
  another_stream: []
}


::Iodine.subscribe(channel: :internal) do |_, json_msg|  
  msg = JSON.parse(json_msg)
  map[msg[:stream]].each do |(channel_id, sockets)|  
    client_message = {identifier: channel_id, message: msg}.to_json
    sockets.each { |s| s.write client_message }
  end
end 

class ChatChannel
  def on_message(data)
    subscribe('chat_stream')
    msg = {stream: 'chat_stream', message: data}
    ::Iodine.publish(channel: :internal, message: msg.to_json)
  end

  def subscribe(stream)
    map[stream]['chat_channel'] << self
  end
end 
```
That is, in fact, we send messages to clients not through `Iodine.publish`, but by making socket.write for suitable sockets (because `socket.write`, as I understood, works asynchronously).

Can you please advice this is an fine solution or it will lead to great downgrade performance? 
And instead of doing a loop with `socket.write` it needs to consider the second `Iodine.publish` for these clients and Channels?


2. The second problem is that `LiteCable.broadcast` can be called outside the current server, that is, from outside Iodine. For example, from another machine, or if only websockets are working through Iodine, and another web app through another server (for example, through puma).
  
  I think this can be done through RedisEngine as pub/sub - then you can write from another machine to Redis.
     But it seems that RedisEngine starts working only after Iodine.start - and this starts the whole server, and if you run this inside another server then it will crash.

  Is it possible to use RedisEngine without starting the server, like a client to a pub/sub engine?
  And another question, is it possible to somehow determine that the current process is running under the Iodine server?


3. The third problem - according to the ActionCable protocol, if no messages have arrived within 6 seconds, then a connection is considered as stale and terminated.

     So you need to send ping messages in format like this
```js
{type: 'ping', time: 132413532432}
```

 Unfortunately, I was not able to do this with `ping` or `on_ping` callbacks (maybe they made not for this purpose?). 
 For now the application has the timer, which sends these messages



So it’s all, sorry for so long post, I’ll be happy to hear your thoughts and hope this will help in future Iodine evolution =)

**Comment by boazsegev** [comment]
Thank you for writing me.

This will be hard to answer all together. I hope I don't miss anything and I hope my answers can help.

> Yes, the problem has gone, thanks!

🎉


> I'm currently working on integrating Iodine as a backend to LiteCable(https://github.com/palkan/litecable/pull/10)...

Wow, sounds great. I hope I can help.

I'm reading more about [ActionCable's design](http://edgeguides.rubyonrails.org/action_cable_overview.html) and I'm trying to figure things out.

It's all new to me, so maybe I'm confused (I didn't use ActionCable before, I prefer Rack over Rails).

> LiteCable (and ActionCable) have stream abstractions ...

How are stream abstractions used when ActionCable connects with Redis?

The [ActionCable Redis adapter code](https://github.com/rails/rails/blob/5fb282239d8ece0eb14121eecfd5446d7aa70343/actioncable/lib/action_cable/subscription_adapter/redis.rb#L25-L35) seems to show that ActionCable streams are mapped to Redis pub/sub channels (sometimes [using a prefix](https://github.com/rails/rails/blob/934327e14ee107d531c8a48e297f74a5cd5eb8bb/actioncable/lib/action_cable/subscription_adapter/channel_prefix.rb#L23-L25)) - as if the stream String is the pub/sub channel name... but maybe I'm missing something?

Maybe Iodine's pub/sub should be used in a similar way, especially because this will allow seamless integration with the Iodine RedisEngine and other ActionCable applications that connect to the same Redis server.


> The first problem is that the method `Litecable.broadcast(stream, message)` works differently than Iodine.publish...
> ...
> for client thats are subscribed for Chat channel 
> 
> ```js
> {identifier: '{"channel":"admin_notification","id":"room_1"}', message: {user: "dima", message: "some", sid: "1521049376518"}}
> ```

What if the "streams" were simply appended to a Channel name, so `{"channel":"admin_notification","id":"room_1"}` will produce a pub/sub channel name such as `admin_notification_room_1` or `admin_notification:room_1`... now you would be able to use pub/sub directly without adding logic or extra processing in the server's code...?

i.e.

```ruby
def broadcast stream, message
  message = message.to_json unless message.is_a? String
  Iodine.publish message: message, channel: "#{stream[:identifier]["channel"]}#{stream[:identifier]["id"].to_s.length ? "_" : ""}#{stream[:identifier]["id"]}"
end
```

> In the current solution, I store all the `stream => [channel, socket]` combinations in the ruby, inside the server process...

This is similar (but not exactly the same) to the way iodine's internal pub/sub engine works.

However, iodine performs a few extra optimizations that you will lose.

For example, assume this situation:

Two servers (A, B) run the same ActionCable (or LiteCable) application, synchronized using Redis.

Server A has 1 subscription to channel `chat`.

Server B has 1 subscription to channel `admin`

(in real life, server A will probably have `chat_user_312`, `chat_user_214`... and server B will have different users, like `chat_user_537`)

Iodine will make sure only server B will receive `admin` pub/sub. This will optimize performance and minimize resource consumption (network load, server CPU load, memory, etc').

However, if we use `internal`, all the servers receive all the messages.

>  `socket.write`, as I understood, works asynchronously.

True.

> 2. The second problem is that `LiteCable.broadcast` can be called outside the current server, that is, from outside Iodine. For example, from another machine, or if only websockets are working through Iodine, and another web app through another server (for example, through puma).
>  
>     I think this can be done through RedisEngine as pub/sub - then you can write from another machine to Redis.

I agree. If you treat iodine's pub/sub exactly the same way as Redis (as if iodine was a Redis server), than using Redis will be as simple as [a single `if` statement](https://github.com/boazsegev/iodine/blob/61177e0d63218c642ed4dbeed449306ed19e8d4e/examples/redis.ru#L12-L17).

> But it seems that RedisEngine starts working only after Iodine.start - and this starts the whole server, and if you run this inside another server then it will crash.
> 
> Is it possible to use RedisEngine without starting the server, like a client to a pub/sub engine?

Oh... I never tried running both servers at once. Iodine has a good HTTP server as well, so I never needed to run both servers in the same process.

The `Iodine.start` method is critical, because it starts the event loop and the IO reactor. Without `Iodine.start` nothing happens.

Theoretically it should be possible to run iodine within Puma, if iodine isn't listening to incoming connections (or is listening on a different port).

I didn't try this, but maybe:

```ruby
on_worker_boot do
  if ENV["REDIS_URL"]
    uri = URI(ENV["REDIS_URL"])
    Iodine.default_pubsub = Iodine::PubSub::RedisEngine.new(uri.host, uri.port, 0, uri.password)
  end
  Iodine.threads = 1
  Iodine.start
end
```

> is it possible to somehow determine that the current process is running under the Iodine server?

Not yet. I can add this feature to the 0.5.0 version. Maybe a function names `Iodine.running?` (or do you think `is_running?` is better?).

Do you need me to backport this to the 0.4.x version as well?

> 3. The third problem - according to the ActionCable protocol, if no messages have arrived within 6 seconds, then a connection is considered as stale and terminated...

Websocket `ping` is part of the Websocket protocol (it's lower level, not JSON) and this is why iodine doesn't let you access the `ping` method for Websockets (it's implemented internally according to the Websocket protocol specifications).

You can set the timeout using iodine's `ws_timeout` feature. Any stale connection will be disconnected after ~ twice the timeout (first timeout will attempt a `ping`, second timeout will notice the error).

The ActionCable ping looks like a higher level JSON "user land" ping.

> For now the application has the timer, which sends these messages

Yes, I think this is the best solution.

You can also create a channel for this, (i.e., `__light_cable_ping`) and register all clients, broadcasting a ping every 6 seconds.

i.e.:

```ruby
Iodine.run_every(6000) {Iodine::PubSub::SINGLE_PROCESS.publish channel: :__light_cable_ping, message: "{type: \"ping\", time: #{Time.now.to_i}}"}
```

---

I'm sorry for my long answer.

I hope my answer was simple and clear. I just started reading about the ActionCable internal structure, so I hope my ideas are helpful.

**Comment by haukot** [comment]
Thank you, it is really helpful!

> The ActionCable Redis adapter code seems to show that ActionCable streams are mapped to Redis pub/sub channels (sometimes using a prefix) - as if the stream String is the pub/sub channel name... but maybe I'm missing something?
> 

I also think it works as you say. Though I can't say that I know ActionCable protocol deeply.

>What if the "streams" were simply appended to a Channel name, so `{"channel":"admin_notification","id":"room_1"}` will produce a pub/sub channel name such as `admin_notification_room_1` or `admin_notification:room_1`... now you would be able to use pub/sub directly without adding logic or extra processing in the server's code...?

Yes, I also thought about this option.
But there is one thing - before sending the client we still need to add the Channel identifier to the message, this part of message:
`identifier: '{" channel ":" admin_notification "," id ":" room_1 "}'`

And for that we can
1) make the Iodine.publish on all existing Channels in the application, even if no one is subscribed to them, and then the function will look like this
```
def broadcast stream, message
  all_app_channels.each do | ch_id |
    message = message.merge ({identifier: ch_id}). to_json unless message.is_a? String
    Iodine.publish message: message, channel: "# {stream [: identifier] [" channel "]} # {stream [: identifier] [" id "]. To_s.length?" _ ":" "} # {Stream [: identifier] ["id"]} "
  end
end
```
But there can be a lot of Channels in the application, so there may be unnecessary messages.

2) store to which Channels and stream users are subscribed and publish only to active Channels. But we store it in Ruby, so it will be the same option with first broadcast to all server processes by internal channel - that is, in fact, we will only replace the socket.write loop with several Iodine.publish calls.

>Theoretically it should be possible to run iodine within Puma, if iodine isn't listening to incoming connections (or is listening on a different port).

Unfortunately Iodine run it’s own server and it blocks connections to Puma. 
Anyway, I can use Redis gem for publish to pub/sub from another machine, but it will be cool if in future it will be possible to using RedisEngine just as client to pub/sub.

>Not yet. I can add this feature to the 0.5.0 version. Maybe a function names `Iodine.running?` (or do you think `is_running?` is better?).

Personally I like `is_running?` , but in different style guides you can find different examples(https://github.com/bbatsov/ruby-style-guide#bool-methods-prefix vs https://github.com/airbnb/ruby#indent-multi-line-bool)

>Do you need me to backport this to the 0.4.x version as well?

This is not something very important, but it would be great.

>You can set the timeout using iodine's `ws_timeout` feature. Any stale connection will be disconnected after ~ twice the timeout (first timeout will attempt a `ping`, second timeout will notice the error).

Oh, okay, thank you for explanation.

>You can also create a channel for this, (i.e., `__light_cable_ping`) and register all clients, broadcasting a ping every 6 seconds.

It’s cool solution, thanks, I’ll try it!

**Comment by boazsegev** [comment]
> before sending the client we still need to add the Channel identifier to the message

I had to do more research and learn more about ActionCable and the way it's using Redis.

I am now convinced that ActionCable streams are mapped directly to Redis pub/sub channels according to the stream name.

According to [this ActioncCable issue](https://github.com/rails/rails/issues/27224), **stream names are actual pub/sub channels and the chanel name is ignored**. The only possible prefix is an application-wide prefix that allows different applications to "namespace" the streams.

In [this post](https://www.codementor.io/victor_hazbun/how-actioncable-uses-redis-4iq2le1i6) it's possible to see how Redis sees published messages (by subscribing to a pub/sub channel matching the stream name).

This shows the pub/sub channel (redis / iodine channel) is equal to the stream name (ActionCable Channel name is ignored) but the message itself in wrapped in JSON (ActionCable Channel name provided in the message, alongside any special parameters).

The same is what I understand after seeing [this YouTube video](https://www.youtube.com/watch?v=n0WUjGkDFS0).

This suggests that the best way to handle pub/sub using iodine might be something similar to this:

```ruby
# stream_from equivalent 
subscribe channel: stream_name

# stream_for equivalent 
subscribe(channel: stream_name) do |_, msg| 
  # message handling here
end

# broadcast equivalent...
message = {identifier:
    { channel: channel_name },
    data: # this is an example data section, they change for each app
          { message: data }
    }
publish channel: stream_name, message: message.to_json
```

Does this approach make sense?

> Personally I like `is_running?` , but in different style guides you can find different examples...

Thanks for the style guide links!

I hope this is okay, but after reading the style guides I believe `Iodine.running?` is more concise. It also fits with `Array#empty?`, which made me feel that the style is a better match for the language.

The other style guide didn't provide any logical explanation for the `is_...?` naming scheme and only required that the method name end with a question mark, giving [`Array#empty?` as an example](https://github.com/airbnb/ruby#naming).
