### ISSUE TITLE
Questions regarding memory handling and process restarts

### ISSUE THREAD

**Issue by matt1e** [boazsegev/iodine#29]
Hi.

My C is a little rusty and I couldn't find much info on it, so I am asking.

How does iodine (or facil.io) handle memory bloat/fragmentation/pollution and restarting processes? I am running a proxy middleware written in Celluloid/Reel that fights with memory fragmentation a lot, despite doing most of the proxying in a C extension that I added. For Puma there is a worker killer that drains the connections and restarts when memory is too high (according to configuration), for Reel I implemented it myself. While I like Celluloid, it's very complex and I was considering to migrate to concurrent-ruby instead, but I don't have many web server options as it seems.

Are there any tools available in iodine that allow you to drain connections and restart the worker? Maybe even automatically? How does it handle memory management in general? I mean we are coming from C-land into Ruby-land and the GC in Ruby is still not very optimal, would it be beneficial to return to C-land? How thread safe is iodine-rack, can I run multiple parallel requests in Ruby-land?

Sorry for the amount of questions, but iodine is far too interesting :)

**Comment by boazsegev** [comment]
Hi @matthias-geier ,

Thank you for opening this issue and for your interest in my projects.

I'm sorry if my answer is a bit long.

### Restarting Workers

Until recently, facil.io and iodine didn't handle this issue. The assumption was that a number of clusters are running behind a load balancer and it would be easy to restart an end-node of there was a need.

With facil.io 0.6.0 this assumption was corrected. Now the `SIGUSR1` (in Ruby `"USR1"`) signal can be used to shut down and restart the worker processes without closing the listening socket. This allows existing HTTP requests to complete and invoke the `on_shutdown` callback for WebSockets.

Iodine adds this feature in version 0.5.0, allowing iodine to restart itself every X milliseconds by adding the following line in the `config.ru` file (or any initialization file):

```ruby
# restart every 4 hours
if defined?(Iodine)
    Iodine.run_every(1000 * 60 * 60 * 4) { Process.kill("USR1", 0) }
end
```

I didn't release iodine version 0.5.0 yet because I'm rewriting the pub/sub API, trying to improve things that the 0.4.x design made difficult to achieve. I hope to release the 0.5.0 version by the end of May.

### Memory Fragmentation

With facil.io 0.6.0 and iodine 0.5.0 (coming soon), a custom memory allocator was designed to deal with concurrent allocations and memory fragmentation.

This improved memory consumption and performance in live testing*.

However, this did not improve the Ruby side of things. Ruby memory still experiences some fragmentation and some apps experience bloating.

The Ruby side of things can only be resolved by restarting the worker processes, as described above.

\* I should point out that iodine 0.5.0 requires more data to be copied since the HTTP layer avoids writing to the sockets while within the GVL), it's also part of the HTTP/2 support roadmap. For this reason iodine 0.5.0 uses more memory than iodine 0.4.x by design.

### Memory design

Memory between C and Ruby has to be copied. Ruby objects have to be marked as "in use" while C objects hold references to Ruby objects.

Iodine uses Ruby memory only for submitting data to the Ruby application and for the `env` template.

In iodine 0.4.x the data was copied directly from and to the buffers used for socket `read` and `write` calls. Starting with iodine 0.5.0 the data is copied to intermediate buffers for validation (after `read`) and concatenation (before `write`).

Since the GC is less than C friendly, iodine provides GC callbacks using a [Registry for Ruby objects](https://github.com/boazsegev/iodine/blob/a0fadae610fc58d2fee95a5c0f3e9c31e6100251/ext/iodine/rb-registry.h). Ruby objects are added and removed from the registry according to their expected lifespans within iodine, protecting Ruby objects against memory corruption.

### Thread Safety

The iodine server should be very thread safe by design, even ignoring the Ruby GIL/GVL.

However, any access to global data should be protected.

Unlike connection specific data, which is protected by the facil.io connection lock and the nature of HTTP, global data might be accessed concurrently by a number of threads and should always be protected from corruption.

As a special case, any data accessed by the `on_ready` WebSocket callback or by a Protocol's `on_ready` and `ping` callbacks should also be protected - `write` connection locks are separate from the task locks used by a connection's task related methods such as `defer`, `on_data`, `on_message`, etc' .


---

I hope I answered everything. If you need me to clarify anything, please let me know.

Kindly,
  B.

**Comment by matthias-geier** [comment]
Wow, that response is awesome! (not only from size but also from content-side)
Thanks for taking the time to clarify all this!

Most of this is very good news, especially how restarting can be handled by uptime, memory footprint or possibly even by CPU usage.
Let's see if I got it right. From a design perspective, there is one listening socket (probably within the main process) and many forks (determined by a variable) that handle incoming connections and the USR1 signal sent to a specific pid is going to shut down that process which is then detected by the main process and it creates a new fork? Is there a list of all worker pids that are currently running? If a worker still takes care of a connection, can you drain that worker or relocate the open connections and then shut down?

What I didn't understand fully is the Registry for Ruby objects. I assume the Ruby objects that end up in the Registry are created within the C extension, and the Ruby objects created by Ruby code in the connection handling, those are still subject to Ruby GC...
Bloat is usually not an issue for me, fragmentation however is. But unless Ruby GC finally decides to compact the memory, this is an issue I will be stuck with while I use Ruby.

Since 0.5 is going to be a little while off, I will probably pick up iodine 0.4 and do a quick prototype with concurrent-ruby to see whether this is going to make my life easier. It looks very much like it, Reel is pretty sweet, but similar to EventMachine you have to understand a lot of what goes on under the hood, which ends up to be really really complex. iodine feels easier :)

**Comment by boazsegev** [comment]
Thank you for your response, I think it helps me learn more about possible use cases and improve the design.

### Hot Restarting a Worker / Server

> From a design perspective, there is one listening socket (probably within the main process) 

Yes.

In addition, each child worker will inherit this listening socket when they are spawned. This means that the listening socket will share the backlog will all the workers.

The root process is mostly a sentinel process, as well as a hub for pub/sub messages (allowing them to cross process boundaries).

> ...many forks (determined by a variable) that handle incoming connections

Yap. Note that the variable is only tested once (during startup). The number of workers isn't updated is the variable is changed during runtime.

> the USR1 signal sent to a specific pid is going to shut down that process which is then detected by the main process and it creates a new fork? 

Exactly... and more.

It's also possible to shut down a specific worker with a SIGINT (or SIGUSR1) sent directly to that worker.

A SIGABRT / SIGSEGV could also be sent to a worker, invoking an immediate crash (no winding down, no shutdown callbacks and requests are dropped immediately).

When the root process detects that a worker stopped while the server is still active (the worker crashed / shutdown), a new worker will be spawned in it's place.

In addition, a SIGUSR1 sent to the main (root) process will **signal all the workers** to gracefully shutdown (causing new ones to be re spawned).

> Is there a list of all worker pids that are currently running?

Hmm... no.

You could add hooks for managing such a list (i.e., using `after_fork` in iodine or the listening socket `on_start` callback in facil.io)... but I find it redundant.

When a CPU/memory issue is detected externally, it's usually possible to find the pid for the offending process.

When using an internal timer, it's simple to detect the process's own pid.

When hot-restarting the whole server, the parent process is the only pid you need (which is easy enough to save in a global variable).

i.e.:

```ruby
if defined?(Iodine)
    # store parent pid
   ROOT_PID = Process.pid
   # defer Iodine.run_every so it's called after iodine forks.
   Iodine.defer do
       # call Iodine.run_every only if the process is the root process
       if ROOT_PID == Process.pid
          # set a timer using Iodine.run_every
          Iodine.run_every(1000 * 60 * 60 * 4) { Process.kill("USR1", ROOT_PID) }
       end
   end
end

```

### Ruby Object Registry

>  I assume the Ruby objects that end up in the Registry are created within the C extension

That's correct... it includes objects created by the C extension as well as objects that are logically "owned" by the C extension (such as callback `Proc` objects).

In the following example, the block of code is a Ruby object that is "owned" by iodine for the duration of the pub/sub subscription, so internally it will be registered (and removed) along with the subscription:

```ruby
subscribe(channel: "my channel") { |ch, mgs| p "channel: #{ch}\n#{msg}" }
```

> Bloat is usually not an issue for me, fragmentation however is. But unless Ruby GC finally decides to compact the memory, this is an issue I will be stuck with while I use Ruby.

facil.io attempts to handle fragmentation using a custom memory allocator, but it's only used internally and doesn't effect the Ruby allocator (which also tries to fight fragmentation, but it's designed to be generic and has a harder job).

You can compile Ruby with `jemalloc` to mitigate the issue, but it's an issue we all have to deal with.

> iodine feels easier :)

Thank you so much!

My intention is to make iodine as transparent as possible. I'm very happy you find the API easy to use ☺️

**Comment by boazsegev** [comment]
> Now for the final question, what does "graceful shutdown" mean for iodine? And what options can you configure?

What do you want it to do? I'm still developing version 0.5.0, so if you need new features, this might be a good time to point them out.

At the moment it calls the `on_shutdown` callbacks for objects that support it (WebSockets and custom Protocol objects) completes any pending events (i.e., `defer` calls, reads any pending IO data, completes any pending HTTP requests) and attempts to flush the sockets before closing them (responses might fail to send if they are too long or the client is too slow, but a decent attempt is made at flushing out any pending data).

Because this is Ruby, any `at_exit` event will (should) eventually be called as well.

> You'd be surprised, but most of our fragmentation originates within redis-rb...

Interesting.

I'm not sure if iodine's integrated Redis engine would help with that (since messages and channel names still creates new String objects), but it might lessen the intermediary object count.

> For clarification, I kind of need to do my own restarting.

Good Luck! Let me know if you need anything!

**Comment by boazsegev** [comment]
P.S.

> iodine makes me want to return to the good old C days again. When 5 days of debugging a mem leak lead to a facepalm instead of frustrated screaming from your rooftop.

😂😂😂

I know exactly what you mean 😂

**Comment by boazsegev** [comment]
> For regular web connections I'd love to have a time to shutdown

You raise a very valid concern about unexpected disconnections and I think our conversation exposes a possible flaw in the graceful shutdown (since it currently only addresses data that's already scheduled to be sent).

I'll see what I can do.

However, I'm afraid quick cleanup is essential on some systems, even though [it's more lax on other systems](https://devcenter.heroku.com/articles/limits#exit-timeout). So I think I might impose a limit on a connection's timeout. Docker's default limit is 10 seconds, which I might adopt.

> the amount of strings being created and garbage collected is quite high, and with Celluloid switching back and forth between those connections, the pollution is amusingly high

Could you explain what you mean by pollution? I'm starting to suspect that we aren't discussing the cache being polluted (which is what I originally thought).

**Comment by matthias-geier** [comment]
> Docker's default limit is 10 seconds, which I might adopt.

This would cover most of the connections. When serving HTTP your connections shouldn't live this long, with a proxy it's a bit different, but 10s is awesome. How do you handle this issue for web sockets where a worker holds hundreds of open connections and the applications rely on them working properly? I presume killing them off immediately is far from ideal too.

> I'm starting to suspect that we aren't discussing the cache being polluted

I was referring to memory pollution in Ruby-land. Not exactly bloat, but chunks of memory that cannot be freed and at one point cannot be reused anymore either because of fragmentation. Whatever you do in C seems to be cleared up and freed just fine :)

When I run regular web apps that are rack based, usually a single connection is completed before taking on the next, and there you rarely see any issues with memory. But when you have concurrency on a larger scale, it does weird things to your memory. That's what I meant. Sorry for not clearing that up better

**Comment by boazsegev** [comment]
> How do you handle this issue for web sockets where a worker holds hundreds of open connections and the applications rely on them working properly?

Actually this is fairly easy.

WebSocket clients expect WebSocket connections to disconnect and often have reconnection logic implemented in the `onclose` client callback.

Iodine 0.5.0 will also send a signal to the client indicating the connection is about to be closed.

> When serving HTTP your connections shouldn't live this long, with a proxy it's a bit different, but 10s is awesome.

I would love your opinion about a design I'm testing out.

What I is a new design that will safely complete any pending requests and make sure all the response data is sent through the socket.

This design has an inherent security flaw, since slow clients could (potentially) delay the shutdown significantly by refusing to receive the data is a reasonable time (this is why today's design doesn't promise to send the whole buffer).

However, adding a `pre_shutdown` callback that sets a time limit can cause a chain reaction where the connection's closure is delayed even further and exposes an additional security concern.

These could result in DoS if exploited by a malicious attacker.

One possible solution is to forcefully close the socket after the specified amount of time. However, this might truncate the outgoing data and more or less brings us back to the same flaws we might experience in the current design (unexpected server disconnection).

My intuition tells me that simpler is better - making a best attempt at sending as much of the existing data as possible (similar to the current design) and allowing clients to handle disconnections as they see fit (all without a timer).

This means that any HTTP Rack style responses will be fully handled since iodine will wait for the response to be handled (as it does today) but responses might not be fully sent before disconnection occurs.

What are your thoughts on the matter?

> chunks of memory that cannot be freed and at one point cannot be reused anymore either because of fragmentation. 

With the amazingly talented people on the Ruby team, I would have imagined fragmentation handling to be better.

I wonder if there's a chance that bits and pieces use a longer than necessary lifetime.

A very good example is the creation of new Symbols (that are long-life objects) within Web requests (so they are placed next to short-life Strings / request data).

This is a common pitfall that occurs when converting JSON or YAML into Ruby objects, since sometimes (often for convenience) we allow Symbols to be created, which could increase fragmentation.

Anyway, just my 2¢.

**Comment by boazsegev** [comment]
> Symbols can be garbage collected since 2.2

They are, but they aren't garbage collected as fast as other objects. They have longer lifetimes.

The classic example is:

```ruby
def my_func
    a = "my_string"
    b = :my_symbol
    nil
end
```

The String should be cleared away immediately (there was a specific garbage collection optimization for that, it should still be there).

The Symbol will be cleared when the GC runs (the optimization won't collect it).

> Usually an attacker wouldn't know when exactly your workers go down or up...

I don't think they need to know.

facil.io and iodine can handle a lot of connections and have very good protection against Slowloris (slow client attacks).

This basically means that the attacker could attempt a day long attack with little inconvenience (although they will drain open file resources).

But, at some point they will eventually hit the weak spot during a worker rotation, unless that weak spot is reinforced.

Am I missing something?

> with a proper proxy frontend (like nginx), he never will.

I wish. But I also want facil.io and iodine to be sturdy enough (at some point) so they aren't fragile when exposed directly to the Web. 

> And this is something that the application developer has to take responsibility for.

I trust you, you write network related code, you know what you're doing.

I'm sorry to say that I don't trust application developers as a matter of policy.

Their job is the application development, I don't expect them to know anything about network programming.

> I don't think this is a bad thing that it's truncated when I have the option to set the timeout to a specific time range.

Will it be okay if the timeout option is hardcoded?

At the moment I implemented this hard timeout concept using a hard-coded  8 seconds timeout (this is a fuzzy 8, so it might be up to ~1.9 seconds longer)... it was easier than breaking the ABI (which means facil.io will need to bump it's version).

The logic behind the timeout is this:

* If facil.io / iodine are running behind a proxy (i.e., nginx), than very large amounts of data should be transferable within 8 seconds. The proxy will cache the data and handle security (as far as I know).

* If facil.io / iodine are running exposed (no proxy), than they should exhibit self preservation techniques. 8 seconds seemed reasonable.

* I assume most clients re-attempt most requests.

What do you think about this approach?

> I also own a SaaS application where data downloads take minutes depending on customer, so there should be support for this, but it shouldn't be the default.

Interesting. I would have assumed that large downloads / uploads would avoid HTTP and use sockets / WebSockets in order to safely resume in case of disconnections.

I know HTTP supports the range requests (which iodine and facil.io support for static file requests), so I guess that's one way to deal with this. However, I never know with HTTP clients, which ones resume and which ones restart.

**Comment by matthias-geier** [comment]
> Am I missing something?

I guess the attacker wouldn't be aware that he's blocking a worker shutdown, so yes, it's annoying, but there shouldn't be a feedback loop to the client telling him that he's found an issue...

> Their job is the application development, I don't expect them to know anything about network programming

A valid point, and I see where you are coming from, but you cannot build middleware that serves a broad audience and is very flexible, and be secure and error prone at the same time. And I'd argue that most application developers don't change the config of their http servers unless they run into issues.

> I assume most clients re-attempt most requests

Having worked in SaaS environments over 5 years now, this assumption is unfortunately not turning out to be true. So many clients build bad software that consume APIs and complain to the service instead of fixing their stuff. If you have conditions in your ToS or client contract, that you need to uphold, then retrying is also something causing problems for you. It's a touchy subject.

> The proxy will cache the data and handle security (as far as I know)

Sometimes caching works, sometimes it doesn't. For instance, when you can configure your spreadsheet download format, precalculation is sometimes impossible, and caching makes no sense because the data probably won't be redownloaded. There are edge cases were you cannot serve cached or precalculated files. I doubt it's the majority, but I have run into them in almost every job I had, and then you needed a solution beyond forking the project and changing the timeout constant. :)


Finally I'd welcome a flexible middleware which I can customize through configuration when I have no other choice. Ultimately it's your choice whether you want to provide those options though, since I can understand your concerns and I'd weigh their pros and cons too.

**Comment by boazsegev** [comment]
> the attacker wouldn't be aware that he's blocking a worker shutdown, so yes, it's annoying, but there shouldn't be a feedback loop to the client telling him that he's found an issue...

Thanks, I didn't think about this.

That's a very valid point when running a larger number of clusters (which is often the case). The more staggered the rotation the less of an issue this becomes. Nice.

> you cannot build middleware that serves a broad audience and is very flexible, and be secure and error prone at the same time.

Yes, that's probably very true... it's just so hard not to try :-)

> And I'd argue that most application developers don't change the config of their http servers unless they run into issues.

This is actually a very good selling point for providing flexibility 👍 

> Having worked in SaaS environments over 5 years now, this assumption is unfortunately not turning out to be true...

Thank you, this is good to know. There's stuff there I didn't consider.

> Sometimes caching works, sometimes it doesn't...

Oh, my bad, I didn't mean "caching" in that sense... I explained it very poorly.

I meant buffering and buffer caching. I meant that the Proxy will not become a slow client just because it's connected to a slow client. It will buffer the whole of the response and wait for the slow client to consume that response.

This means that 8 seconds is a lot of time to send any pending responses.

> Ultimately it's your choice whether you want to provide those options...

I know, but it  helps to brain storm with the people that use my code. After all, I want to provide something you'll love.

Thank you for taking the time to respond and brain storm with me. I'll try to figure out a design for your feature request and see what I can come up with.
