### ISSUE TITLE
Req: SignalR implementation

### ISSUE THREAD

**Issue by bleedr** [boazsegev/iodine#31]
How can the wss be used with SignalR?
I'm trying to connect to https://github.com/Bittrex/bittrex.github.io but I just can't get it to work.

**Comment by boazsegev** [comment]
Hi @bleedr ,

Thank you for opening this feature request.

If I understand you correctly, you are hoping to implement a SignalR **client** using iodine.

At the moment, client mode isn't properly supported by iodine due to lacking TLS/SSL support for client side IO.

However, [client support is on the roadmap for facil.io](https://github.com/boazsegev/facil.io/blob/master/CONTRIBUTING.md#where-to-start--roadmap). Once facil.io has an API for TLS/SSL client connections I'll start working on authoring a Ruby API for iodine.

In the meantime, you can either use a different library for client side code or write your own insecure client with iodine using [the `Iodine.connect` method](http://www.rubydoc.info/github/boazsegev/iodine/master/Iodine#connect-class_method) (by implementing your own Protocol class to encode/decode WebSocket data).

**Comment by boazsegev** [comment]
Client connections with TLS are now supported - closing issue.

**Comment by Davidzhu001** [comment]
@boazsegev thanks so much!
