### ISSUE TITLE
Segfault with ruby-2.4

### ISSUE THREAD

**Issue by ojab** [boazsegev/iodine#45]
```
git clone git@github.com:can-i-has-a-job-plz/litecable.git
cd litecable
bundle
IODINE=1 bundle exec rspec
# => Segmentation fault (core dumped)
```
backtrace looks like
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1b5d7e547d in rb_call (scope=CALL_FCALL, argv=0x352b1a0, argc=1, mid=4321, recv=28227120) at vm_eval.c:841
841         return rb_call(recv, mid, n, argv, CALL_FCALL);
[Current thread is 1 (Thread 0x7f1b4f800700 (LWP 13035))]
```
but I'm not really sure that it's useful (it's around 8k frames for segfaulted thread). Reproducible here on Fedora-29 x86_64 & on travis ci (some ubuntu, x86_64).

**Comment by boazsegev** [comment]
I originally managed to recreate the issue, not on macOS, just on Linux distributions. 

On macOS, I'm getting the error:

```none
#<Thread:0x00007f8659aff190@/.../litecable-master/spec/integrations/server_spec.rb:128 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
undefined method `message' for 8:Integer (NoMethodError)
```

I'm still trying to figure out how to debug this issue on Linux. Meanwhile I'm hunting "blind", trying to add type checks and edge case reviews where I can.

**Comment by ojab** [comment]
Yeah, I'm also getting `undefined method `message' for 8:Integer (NoMethodError)` using ruby 2.5 on linux, but I wasn't sure if it's user (mine) error or an actual issue.

**Comment by boazsegev** [comment]
It could be an issue if the object is passed to iodine as a response. 

Iodine doesn't test the application's response object's type or it's internal structure. It assumes that it's an Array with 3 objects and that these objects are correctly typed.

I'll add type checks, to avoid bad response types from crashing the system...

Until now I was using this to discover application issues (where an invalid response was returned). I guess I like it when things crash, so I know something was wrong without looking too hard. But I guess this isn't super polite.

**Comment by boazsegev** [comment]
I'm not sure this is related to the current issue. I'm still trying to figure it out.

**Comment by boazsegev** [comment]
I think it's fixed now... see the PR submitted to the can-i-has-a-job-plz/litecable repo.

Let me know.

**Comment by boazsegev** [comment]
P.S. I also released another patch, iodine 0.7.8, which tests for application return types and fixes a possible issue with `unsubscribe`.

**Comment by boazsegev** [comment]
Hmm... I can't really reproduce on Ubuntu, I ran the test a lot of times before I got an error, but that wasn't the error (something about RSpec's linked list and later a hanging / waiting process)... Is this only on Fedora?

**Comment by ojab** [comment]
yep, fedora-29 & ruby installed via rvm.

**Comment by ojab** [comment]
I'll try on ubuntu later and close if it cannot be reproduced.

**Comment by boazsegev** [comment]
I'll install Fedora later tonight and try it out. I want iodine to work on any Linux distribution if possible. Also, this might  expose a bug that is simply hiding right now.

May I ask what the tests are doing (I'm not sure I understand everything that's going on, maybe it's because I'm not sure how the Cable is behaving)?

I'm asking because it could allow me to construct a C level test and follow it before testing the Ruby layer bridge, which will make testing and debugging easier.

**Comment by boazsegev** [comment]
Thank you very much for the output log and your patience! 🙏🏻

I installed fedora 29 (which took me a while to manage, as it's new for me).

I also updated the Specs to allow iodine to finish it's startup process (otherwise I kept getting client failures):

```ruby
context 'IodineServer', :async, if: ENV['IODINE'] do
  include_examples 'Lite Cable server' do
    before(:all) do
      Iodine.workers = 1
      Iodine.threads = 4
      @server = Thread.new do
        Iodine::Rack.run(
          LiteCable::Server::Middleware.new(nil, connection_class: ServerTest::Connection),
          Port: '3099', Address: '127.0.0.1'
        )
      end
      sleep(0.5)
    end

    after(:all) do
      Iodine.stop
     @server.join
    end
  end
end
```

I finally managed re recreate the issue using the above code 🎉

I made a few changes to the IO thread initialization code and this seems to have fixed the issue 👍🏻

...

I'm releasing iodine version 0.7.9, which seems to work properly... but I'm leaving the issue open...

It was hard to recreate the issue and I'm not 100% sure if I solved the bug or if I just stoped being able to recreate the issue.

Please let me know.

**Comment by ojab** [comment]
Thanks a lot! Looks like 0.7.9 solves the issue, I cannot reproduce it anymore.

**Comment by boazsegev** [comment]
Thanks for letting me know!

And thank you for exposing this issue!

🙏🏻👍🏻
