### ISSUE TITLE
Make ctrl-c play nicely with capybara

### ISSUE THREAD

**Issue by ianks** [boazsegev/iodine#59]
currently when using iodine capybara-rspec, ctrl-c does not seem to be propogated properly back to rspec, so the specs will continue to run. if you press ctrl-c again, the tests will immediately stop and not inform the user which tests failed. 

it would be great if iodine had the same behavior as puma here, where ctrl-c would be delegated to rspec so it would inform the user which specs failed.

**Comment by boazsegev** [comment]
Hi @ianks ,

Thank you for opening this issue.

I authored a patch on the git master branch that would allow signals to propagate to pre-exiasting handlers (I assume this will lead to the Ruby signal handling code).

I didn't release the patch yet, since I don't have time to properly test it tonight. Feel free to try it out and let me know by installing iodine from the git master branch.

In a Gemfile this can be done by including iodine like so:

```ruby
gem 'iodine', git: 'https://github.com/boazsegev/iodine'
```

I think it's also possible to use the `gem specific_install` command in the terminal:

```bash
gem specific_install -l https://github.com/boazsegev/iodine.git
```

Good luck! I hope this solves your issue. Please keep me posted.

Kindly,
  Bo.

**Comment by ianks** [comment]
Works swimmingly! Thank you!

**Comment by vitobotta** [comment]
HI! I am testing iodine now and I'm having this issue with the latest version. What can I do? Thanks!

**Comment by boazsegev** [comment]
@vitobotta ,

This issue was fixed by forwarding the SIGINT and SIGTERM signal(s) to any active Ruby trap. Could you open a new issue describing what isn't working and how iodine is failing?

Thanks.
