### ISSUE TITLE
Would it be feasible to implement request coalescing?

### ISSUE THREAD

**Issue by giovannibonetti** [boazsegev/iodine#62]
I'm having a great experience with iodine in production in my (small) company and I'm wondering how to extend Iodine to solve an issue we are having. We have some misbehaving (web) clients that ocasionally send a burst of duplicated requests to an expensive endpoint - a server even crashed because of that - and we're looking into a solution to avoid wasting resources with them.

The easier solution is to use something like [rack-attack](https://github.com/kickstarter/rack-attack) and just drop these requests from misbehaving clients with a 429 error. However, I was wondering if there is a way to implement some request coalescing logic [like this](https://github.com/go-chi/httpcoala) to avoid showing an error page when this kind of thing happens. It would have to be implemented either in the load balancer (which is not managed by us) or in the application server. Another way of solving the problem would be inserting another reverse proxy in front of the application like Nginx or Caddy, but I wonder if that would be overkill.

Is there a way of doing some kind of request coalescing / collapsing with Iodine? 🤔

**Comment by boazsegev** [comment]
Hi @giovannibonetti ,

Thank you for opening this issue and for your writing me about your positive experience with iodine.

I am also very concerned to read that burst requests to an expensive endpoint could result in DoS (a server that crashed).

I would love to fix that or offer a solution that works.

Which iodine version are you running? Could you send me a copy of the core-dump / log (if it's iodine that crashed)?

The latest version (0.7.25) has a bit of [request throttling logic built-in to the HTTP/1.1 engine](https://github.com/boazsegev/iodine/blob/356e8e891505196de0727ea015f2830c852547fa/ext/iodine/http1.c#L679-L681), preventing a single connection from accumulating more than 5 buffered requests.

I don't known if this would help logic will solve anything, but it might mitigate the issue (at least, minimizing the chance of DoS).

Iodine also supports timers, which should allow each worker to manage an internal response cache for CPU intensive computations that can't be baked as a static resource. For example:

```ruby
require 'iodine'

class FooCache
  def initialize
    refresh()
    # refreshed every 1 second (1000 mili)
    Iodine.run_every(1000, &self.method(:refresh))
  end

  def response
    @cached
  end

  def refresh
    tmp = "".dup
    tmp << "The time is:"
    tmp << Time.now.to_s
    tmp = [200, {"Content-Length" => tmp.length}, tmp]
    old = @cached
    # objects are a C type VALUE, which fits in a single CPU word, making this replacement atomic on most systems.
    # however, some systems might experience errors unless a Mutex is used both here and in the reader
    @cached = tmp
  end
end

CACHED_BAR = FooCache.new

module APP
  def call(env)
    ::CACHED_BAR.response
  end
  extend self
end

Iodine.listen url: 'http://0.0.0.0:3000', handler: APP
Iodine.threads = 1
Iodine.workers = 2
Iodine.start
```

I'm not sure if this could solve your use-case, but it should improve performance if the response is dynamic but can still be cached for a little while.

> Is there a way of doing some kind of request coalescing / collapsing with Iodine?

I can't imagine implementing something like Go's [httpcoala](https://github.com/go-chi/httpcoala), since it's only relevant for some applications and some paths (but not others).

A safer approach I would consider would be to implement a response cache, such as utilized by a reverse proxy... but I believe that applications that exhibit these requirements should probably use a reverse proxy anyway - which means wasted resources (cache memory) for applications that do use a reverse proxy.

In fact, I highly recommend using a reverse proxy, such as nginx, as an extra layer of defense (assuming the reverse proxy itself doesn't add security risks). 

Because reverse proxies are only network bound, they don't have to deal with running potentially risky (or CPU intensive) user code. This allows them to focus computation time on other beneficial tasks.

**Comment by giovannibonetti** [comment]
Hi, @boazsegev! Thanks for the quick reply!

> Which iodine version are you running? Could you send me a copy of the core-dump / log (if it's iodine that crashed)?

Actually the server didn't really crash, it just ran out of threads because the misbehaving client used up all of them and then the app stopped responding to new requests. We are using version Iodine version 0.7.24 but don't worry about it, Iodine worked fine. I'll upgrade to version 0.7.25 to see if the throttling helps.

> Iodine also supports timers, which should allow each worker to manage an internal response cache for CPU intensive computations that can't be baked as a static resource. For example:

That's an interesting take. I'm glad to know Iodine supports that. However I guess the cache would only work after the first request finished, then the following requests would be able to consume the cached value. In my use case a lot of duplicated requests got to the server before the first one finished, so the cache would not be ready on time.

> A safer approach I would consider would be to implement a response cache, such as utilized by a reverse proxy... but I believe that applications that exhibit these requirements should probably use a reverse proxy anyway - which means wasted resources (cache memory) for applications that do use a reverse proxy.
>
> In fact, I highly recommend using a reverse proxy, such as nginx, as an extra layer of defense (assuming the reverse proxy itself doesn't add security risks).
>
> Because reverse proxies are only network bound, they don't have to deal with running potentially risky (or CPU intensive) user code. This allows them to focus computation time on other beneficial tasks.

You are right, a reverse proxy that's probably a better approach. Our app is running on App Engine Flex, which already has an Nginx container in front of it which we can't customize, so I'll try something else before adding another proxy in front of the app server.

Anyway, it was a very rare case that caused the DoS to our server so I'll try not to worry too much about it. I'll try using [rack-attack](https://github.com/kickstarter/rack-attack) to help throttling requests from misbehaved clients. If that doesn't solve the problem I'll look into adding a customized Nginx proxy or similar.

Thanks for giving your take on the problem. 👍
