### ISSUE TITLE
Ability to disable last-modified being set?

### ISSUE THREAD

**Issue by ianks** [boazsegev/iodine#65]
Is it possible to disable the automatic addition of last-modified on certain routes? we are using etags on certain controllers so we do not want to have the last-modified  checked. is this possible?

**Comment by boazsegev** [comment]
IMHO, the `last-modified` header should be considered a required header (rather than an optional one) for data driven applications. This is extra true where SEO is concerned.

In the MDN, they state that [this header is a fallback mechanism](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) for the `etag` header.

Iodine will only [fill in the `last-modified` header if it's missing](https://github.com/boazsegev/facil.io/blob/e649091a1de13ef4a83e1b3911dcdc93d389a7ea/lib/facil/http/http.c#L113-L117) (or, at least, that's how the code is supposed to behave).

I'm open to listen as to why the header might be redundant and should be removed. Things may have changed since I made the decision to automatically add the header when missing.

The fastest (most immediate) solution should be to fill in the correct `last-modified` header when setting the `etag`.

Please note that the `last-modified` header is very helpful for intermediaries and search engines. `etag` headers are great, but they don't indicate the last time a resource was updated (for example, when searching for newer or older information or when searching for an article from 2017).
