### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by janbiedermann** [boazsegev/iodine#77]
Hi Bo,
It looks like iodine provides and uses a storage thats shared across workers.
I would like to use that storage.
I got until here: https://github.com/boazsegev/iodine/blob/2de5878d72a7f6c148ae6ef8627c647c5817502b/ext/iodine/iodine_store.c#L139
But trying to access this ivar i failed.
How can i use the storage?

**Comment by janbiedermann** [comment]
From ruby i meant. I tried Iodine.instance_variable_get(:@storage) to access it, no success.

**Comment by boazsegev** [comment]
Hi @janbiedermann ,

Thank you for your question.

> It looks like iodine provides and uses a storage thats shared across workers.

Please allow me to clarify, because this storage might not be what you hope it is.

The storage isn't really shared across workers. It's part of the internal Ruby<=>C bridge and memory management system.

When Ruby objects are moved to C land, the GC in Ruby can't see them and they might be prematurely deallocated.

The storage class is a virtual Ruby object that references all the hidden Ruby objects in order for them to be visible to the GC.

It's basically a C Hash Map / Set filled with Ruby objects that gets all of them marked as used every time the GC runs.

I hope this explains the situation a little better.

> How can i use the storage?

If you want to store variables outside of the workers, something that can be shared across processes, I would recommend you use Redis or some other database for that.

Alternatively, you could synchronize a common cache across workers using pub/sub (at the cost of memory duplication).

I'm not sure if Ruby has other IPC primitives that could help with that, but I think it does.

Good luck!
   Bo.

**Comment by janbiedermann** [comment]
Thanks for the explanation 👍 
In fact, i was hoping to provide a simple setup for isomorfeus without the need for a external database. Ill look further.
