### ISSUE TITLE
fatal error: 'errno.h' file not found

### ISSUE THREAD

**Issue by tarellel** [boazsegev/iodine#79]
**Version that works:** `0.7.33`
**Version with issues:** `Any version > then 0.7.33. (0.7.34 & 0.7.35)`

**RubyVersion:** `2.6.2`
**OpenSSL Version:** `OpenSSL 1.1.1d  10 Sep 2019`
**O/S:** `macOS 10.14.6`

When running `gem install iodine`, `bundle install`, and/or `gem install iodine -v '0.7.35' --source 'https://rubygems.org/'`

```ruby
Installing iodine 0.7.35 (was 0.7.33) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/tarellel/.rvm/gems/ruby-2.6.2@search/gems/iodine-0.7.35/ext/iodine
/Users/tarellel/.rvm/rubies/ruby-2.6.2/bin/ruby -I /Users/tarellel/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0 -r ./siteconf20191023-752-jjl89t.rb extconf.rb
checking for clang... yes
testing clang for stdatomic support...
using clang compiler v. 9.0.0
.
detected `kqueue`
checking for -lcrypto... yes
checking for -lssl... yes
detected OpenSSL library, testing for version and required functions.
confirmed OpenSSL to be version 1.1.0 or above (OpenSSL 1.1.1d  10 Sep 2019)...
* compiling with HAVE_OPENSSL.
creating Makefile

current directory: /Users/tarellel/.rvm/gems/ruby-2.6.2@search/gems/iodine-0.7.35/ext/iodine
make "DESTDIR=" clean

current directory: /Users/tarellel/.rvm/gems/ruby-2.6.2@search/gems/iodine-0.7.35/ext/iodine
make "DESTDIR="
compiling fio.c
In file included from fio.c:8:
./fio.h:205:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^~~~~~~~~
1 error generated.
make: *** [fio.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/tarellel/.rvm/gems/ruby-2.6.2@search/gems/iodine-0.7.35 for inspection.
Results logged to /Users/tarellel/.rvm/gems/ruby-2.6.2@search/extensions/x86_64-darwin-18/2.6.0/iodine-0.7.35/gem_make.out

An error occurred while installing iodine (0.7.35), and Bundler cannot continue.
Make sure that `gem install iodine -v '0.7.35' --source 'https://rubygems.org/'` succeeds before bundling.
```

**Comment by adam12** [comment]
What's the output of `xcode-select -p`?

Nothing really sticks out between the versions you posted that would indicate a breaking change that's causing the error.

Just to confirm, `gem install iodine -v '0.7.33'` finishes without error?

**Comment by tarellel** [comment]
Output from `xode-select -p` is `/Applications/Xcode.app/Contents/Developer`.

**Comment by boazsegev** [comment]
Hi @tarellel ,

The `errno.h` header belongs to the standard C library (libc) that comes with the compiler.

The `errno.h` header is the first "system" header that the C code requests (since the `include` statements are alphabetized).

The error you're experiencing indicates that **something is wrong with the setup for the developer toolchain** (compiler / path / etc').

This would be very similar to [the issue described here](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave) only with a different system header.

The reason @adam12 asked you to confirm that `gem install iodine -v '0.7.33'` works on the same machine is to test the toolchain. This will allow us to search for the issue higher up the chain (thanks @adam12 ).

The [code changes between the 0.7.33 version and the 0.7.35 version](https://github.com/boazsegev/iodine/compare/v0.7.33...v0.7.35) don't seem to include anything that should effect that change.

Please confirm if `gem install iodine -v '0.7.33'` works on the same machine and let us know if you can provide any more details.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
@tarellel  - Any updates on this?

Did you attempt starting the `Xcode` application (it might show an installation dialog box if some things are missing / require an update)...?

Did you attempt [the solution suggested in StackOverflow](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave)?

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Closed due to lack of response.
